### PR TITLE
Cleanup system files and add .gitignore

### PR DESCRIPTION
**Pull request by dirk**
Spring cleaning in December. :raised_hands:

### CODE REVIEW

**Comment by cathschmidt** [comment]
yeah we're all n00bs here so

**Comment by dirk** [comment]
@cathschmidt: What I lack in zany creativity I make up for with anal retentive repository and file organization. :smile:

**Comment by dirk** [comment]
At least there's a way everyone can contribute!

**Comment by cathschmidt** [comment]
;) I'm sure something interesting will appear here from you

**Pull request merged**
